FROM node:22-slim

WORKDIR /app

# Install deps
COPY package*.json ./
RUN npm install

# Copy source
COPY ./ ./

# Build for production
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

EXPOSE 3000

CMD ["npm","run","start"]
